trigger:
- main

#pool:
#  name: Default
#  demands:
#  - agent.name -equals AgentSelfHosted

pool:
  vmImage: 'windows-latest'

steps:
- task: AdvancedSecurity-Codeql-Init@1
  inputs: 
    languages: 'javascript' 
  displayName: 'Advanced Security Initialize CodeQL'   

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.8.0'
  inputs:
    versionSpec: 5.8.0

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '**/*.sln'

- task: MSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '**/*.sln'
    msbuildArguments: '/p:Configuration=Release'

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd reactapp
    npm install
    npm run build
  displayName: 'Build React App'

- task: DotNetCoreCLI@2
  displayName: 'Build .NET WebAPI Project'
  inputs:
    command: 'build'
    projects: '**/webapi.csproj'
    arguments: '--configuration Release'

- task: AdvancedSecurity-Dependency-Scanning@1 
  displayName: 'Advanced Security Dependency Scanning' 

- task: AdvancedSecurity-Codeql-Analyze@1 
  displayName: 'Advanced Security Code Scanning' 
